baseURL = 'https://patrick85081.github.io/'
languageCode = 'zh-TW'
title = '派翠克技術手札'
theme = 'm10c'

[params]
  author = "Patrick"
  description = "這裡是一位接觸過AOI、電控軟體、安卓移動端、WPF、Asp.Net什麼都學的派翠克，熱愛C#語言帶來的方便與美好，雖不喜歡JavaScript但也不排斥，從Jave和Kotlin身上啟蒙設計模式的真諦，將日常所見所聞記錄下來的技術手札。"
  avatar = 'avatar.png'

[menu]
  [[menu.main]]
    identifier = "home"
    name = "首頁"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "標籤"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "search"
    name = "文章搜尋"
    url = "/search/"
    weight = 3


[[params.social]]
  icon = "github"
  name = "Github"
  url = "https://github.com/patrick85081"
[[params.social]]
  icon = "rss"
  name = "Rss"
  url = "/index.xml"
[[params.social]]
  icon = "mail"
  name = "聯絡我"
  url = "mailto:patrick85081@gmail.com"


[outputs]
  home = ["HTML", "RSS", "JSON"]